name: MATLAB tests

on:
  push:
    branches:
            - main
            - CI
  pull_request:
    branches:
            - main


jobs:

  run-matlab-test:

    name: Install dependencies and run MATLAB tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab_version: [R2021a, R2021b, latest]
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab_version }}

      - name: Clone mystica
        run: |
          git clone https://github.com/ami-iit/mystica.git

      - name: Install mystica
        uses: matlab-actions/run-command@v1
        with:
          command: |
            cd mystica
            install('env_name','imorph')

      - name: Test linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          /home/runner/work/paper_bergonti_2022_tro_kinematics-control-morphingcovers/paper_bergonti_2022_tro_kinematics-control-morphingcovers/mystica/deps/condabin/mamba

      - name: Run MATLAB tests
        uses: matlab-actions/run-command@v1
        with:
          command: |
            ls
            cd mystica
            ls
            cd deps
            ls
            setup
            path
            run(fullfile('mystica','deps','setup'))
            run(fullfile('scripts','test_ci'))
            
